### ISSUE TITLE
Is there a corresponding paper to this project?

### ISSUE THREAD

**Issue by wadx2019** [antoniosValmas/V2G-Predictor#2]

**Comment by antoniosValmas** [comment]
There is a corresponding paper, however it is in Greek
http://artemis.cslab.ece.ntua.gr:8080/jspui/bitstream/123456789/18073/1/thesis.pdf

**Comment by wadx2019** [comment]
All right, is that your graduation thesis?

**Comment by antoniosValmas** [comment]
Yes, it is
